import type { ConfigModuleDefinition } from "@/lib/config-dashboard/types";

/** Catalog of every Phase 1 configuration module for the command centre. */
export const CONFIG_DASHBOARD_MODULES: ConfigModuleDefinition[] = [
  {
    id: "school_branding",
    name: "School branding",
    engine: "E07",
    description: "School name, board, address, logo, feature flags.",
    href: "/onboarding/school-identity",
    libPath: "lib/config/school-branding*",
    requiredForOnboarding: true,
  },
  {
    id: "academic_calendar",
    name: "Academic calendar",
    engine: "E08 / E17",
    description: "Years, terms, working days, holidays, calendar events.",
    href: "/dashboard/calendar",
    libPath: "lib/calendar/**",
    requiredForOnboarding: true,
  },
  {
    id: "structure",
    name: "Classes & sections",
    engine: "E09",
    description: "Year structure: classes, sections, capacity.",
    href: "/onboarding/classes-sections",
    libPath: "lib/onboarding (structure)",
    requiredForOnboarding: true,
  },
  {
    id: "subjects",
    name: "Subjects",
    engine: "E07",
    description: "Subject master, groups, class offers, dependencies.",
    href: "/onboarding/subjects",
    libPath: "lib/subjects/** + lib/config/subjects*",
    requiredForOnboarding: true,
  },
  {
    id: "grading_scales",
    name: "Grading scales",
    engine: "E07",
    description: "Versioned mark schemes / grade bands.",
    href: "/dashboard/configuration#grading_scales",
    libPath: "lib/config/grading-scales*",
  },
  {
    id: "houses_clubs",
    name: "Houses & clubs",
    engine: "E07",
    description: "House/club catalogues, TIC, memberships.",
    href: "/dashboard/houses-clubs",
    libPath: "lib/houses-clubs/**",
  },
  {
    id: "departments",
    name: "Departments",
    engine: "E05",
    description: "Departments, memberships, teaching assignments.",
    href: "/dashboard/configuration#departments",
    libPath: "lib/departments/**",
  },
  {
    id: "timetable",
    name: "Timetable",
    engine: "E10",
    description: "Grids, periods, slots, availability, locks.",
    href: "/onboarding/timetable",
    libPath: "lib/timetable/**",
  },
  {
    id: "assessment",
    name: "Assessment configuration",
    engine: "E11",
    description: "Exam types, definitions, components, publish/lock (no marks).",
    href: "/dashboard/configuration#assessment",
    libPath: "lib/assessment/**",
  },
  {
    id: "report_cards",
    name: "Report card templates",
    engine: "E20",
    description: "Boards, scopes, blocks, assessment refs (no PDF).",
    href: "/dashboard/configuration#report_cards",
    libPath: "lib/report-cards/**",
  },
  {
    id: "policies",
    name: "School policies",
    engine: "E07",
    description: "Versioned attendance, promotion, timings, leave, behaviour rules.",
    href: "/dashboard/configuration#policies",
    libPath: "lib/policies/**",
  },
  {
    id: "communications",
    name: "Communication configuration",
    engine: "E18",
    description: "Categories, channel templates, audiences, delivery/approval rules.",
    href: "/dashboard/configuration#communications",
    libPath: "lib/communications/**",
  },
  {
    id: "editing_framework",
    name: "Editing framework",
    engine: "E28 cross-cut",
    description: "Audit log + config change history health.",
    href: "/dashboard/configuration#editing_framework",
    libPath: "lib/editing/**",
  },
];
